# Generated by Django 4.2.20 on 2025-05-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
