# Generated by Django 4.2.20 on 2025-05-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_customer_user_category_icon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
